# TODO: instead of render command use cat in file ?

# Snake minigame
bind b \
  set -g status-right '#(~/.local/bin/braille-snake -t render)' \;\
  run-shell '~/.local/bin/braille-snake -t init -c 10 >/dev/null; tmux refresh-client -S' \;\
  set -g status-right-length 10 \;\
  switch-client -T snake \;\
  display-message 'Snake mode'

bind -T snake Up    run-shell '~/.local/bin/braille-snake -t up; tmux refresh-client -S' \; switch-client -T snake
bind -T snake Down  run-shell '~/.local/bin/braille-snake -t down; tmux refresh-client -S' \; switch-client -T snake
bind -T snake Left  run-shell '~/.local/bin/braille-snake -t left; tmux refresh-client -S' \; switch-client -T snake
bind -T snake Right run-shell '~/.local/bin/braille-snake -t right; tmux refresh-client -S' \; switch-client -T snake

bind -T snake q \
  run-shell '~/.local/bin/braille-snake -t quit >/dev/null' \;\
  set -g status-right 'refresh' \;\
  set -g status-right-length '10' \;\
  switch-client -T prefix \;\
  display-message 'Snake mode off'

bind -T snake Escape \
  run-shell '~/.local/bin/braille-snake -t quit >/dev/null' \;\
  set -g status-right 'refresh' \;\
  set -g status-right-length '10' \;\
  switch-client -T prefix \;\
  display-message 'Snake mode off'
