# TODO: instead of render command use cat in file / variable

# Snake minigame
bind b \
  set -g @snake_active 1 \; \
  set -g status-right '#{?@snake_active,#[fg=brightgreen]#(~/.local/bin/braille-snake -t render)#[default],refresh}' \; \
  set -g status-right-length 10 \; \
  run-shell '~/.local/bin/braille-snake -t init -c 10 >/dev/null' \; \
  switch-client -T snake \; \
  refresh-client -S \; \
  display-message 'Snake mode'

bind -T snake Up    run-shell '~/.local/bin/braille-snake -t up >/dev/null'    \; refresh-client -S \; switch-client -T snake
bind -T snake Down  run-shell '~/.local/bin/braille-snake -t down >/dev/null'  \; refresh-client -S \; switch-client -T snake
bind -T snake Left  run-shell '~/.local/bin/braille-snake -t left >/dev/null'  \; refresh-client -S \; switch-client -T snake
bind -T snake Right run-shell '~/.local/bin/braille-snake -t right >/dev/null' \; refresh-client -S \; switch-client -T snake

bind -T snake q \
  run-shell '~/.local/bin/braille-snake -t quit >/dev/null' \; \
  set -gu @snake_active \; \
  set -g status-right 'refresh' \; \
  set -g status-right-length 10 \; \
  switch-client -T root \; \
  refresh-client -S \; \
  display-message 'Snake mode off'
bind -T snake Escape \
  run-shell '~/.local/bin/braille-snake -t quit >/dev/null' \; \
  set -gu @snake_active \; \
  set -g status-right 'refresh' \; \
  set -g status-right-length 10 \; \
  switch-client -T root \; \
  refresh-client -S \; \
  display-message 'Snake mode off'
